### ISSUE TITLE
Invalid value for orientation (0)

### ISSUE THREAD

**Issue by speeddragon** [pragdave/exexif#12]
I was testing this library with a file taken by an LG-H440n device, and it gave the following error.

```
** (FunctionClauseError) no function clause matching in Exexif.Decode.orientation/1    
    
    The following arguments were given to Exexif.Decode.orientation/1:
    
        # 1
        0
    
    Attempted function clauses (showing 8 out of 8):
    
        defp orientation(1)
        defp orientation(2)
        defp orientation(3)
        defp orientation(4)
        defp orientation(5)
        defp orientation(6)
        defp orientation(7)
        defp orientation(8)
    
    (exexif 0.0.5) lib/exexif/decode.ex:103: Exexif.Decode.orientation/1
    (exexif 0.0.5) lib/exexif/decode.ex:13: Exexif.Decode.tag/3
    (exexif 0.0.5) lib/exexif.ex:111: Exexif.read_tags/5
    (exexif 0.0.5) lib/exexif.ex:67: Exexif.read_exif/1
```

The issue is because the orientation value is 0, that appears to be related with [this](https://stackoverflow.com/questions/13245556/exif-orientation-tag-value-always-0-for-image-taken-with-portrait-camera-app-and). 

Should this library accept `orientation(0)`?

**Comment by am-kantox** [comment]
#13
